apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: {{ .Release.Name }}-collector
spec:
  image: {{ .Values.collector.image }}
  ports:
    - port: 8888
  env:
    {{- toYaml .Values.collector.env | nindent 4}}
  config: |
    exporters:
      {{- toYaml .Values.collector.config.exporters | nindent 6 }}
    receivers:
      # Note that this configuration is specific to using the OTel collector
      # with the prometheus receiver.
      prometheus:
        config:
          scrape_configs: {{ .Files.Get "scrape_configs.yaml" | nindent 10 }}
          - job_name: otel-collector
            scrape_interval: 5s
            static_configs:
            - targets:
              - 0.0.0.0:8888

    processors:
      {{- toYaml .Values.collector.config.processors | nindent 6 }}
    service:
      {{- toYaml .Values.collector.config.service | nindent 6 }}
  resources:
    {{- toYaml .Values.collector.resources | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-collector
rules:
- apiGroups: [""]
  resources:
  - nodes
  - nodes/proxy
  - nodes/metrics
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs: ["get", "list", "watch"]
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs: ["get", "list", "watch"]
- nonResourceURLs: ["/metrics", "/metrics/cadvisor"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-collector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-collector
subjects:
- kind: ServiceAccount
  # quirk of the Operator
  name: {{ .Release.Name }}-collector-collector
  namespace: {{ .Release.Namespace }}