{{ range $_, $collector := .Values.collectors -}}
{{ if $collector.enabled }}
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: "{{ $.Release.Name }}-{{ $collector.name }}"
spec:
  mode: {{ $collector.mode }}
  image: {{ $collector.image }}
  replicas: {{ $collector.replicas | default 1 }}
  ports:
    - name: "metrics"
      protocol: TCP
      port: 8888
{{- if eq $collector.mode "statefulset" }}
  targetAllocator:
    enabled: true
    image: $collector.targetallocator.image
    serviceAccount: {{ $.Release.Name }}-collector-targetallocator
    prometheusCR:
      enabled: $collector.targetallocator.prometheusCR.enabled
{{- end }}
  env:
    {{- toYaml $collector.env | nindent 4}}
    - name: KUBE_NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: KUBE_POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
  config: |
    exporters:
      {{- toYaml $collector.config.exporters | nindent 6 }}
    receivers:
      {{- toYaml $collector.config.receivers | nindent 6 }}
      {{ if $collector.scrape_configs_file }}
      prometheus:
        config:
          scrape_configs: {{ $.Files.Get $collector.scrape_configs_file | nindent 10 }}
          {{- if (not (eq $collector.mode "statefulset")) }}
          - job_name: otel-collector
            scrape_interval: 5s
            static_configs:
            - labels:
                collector_name: ${KUBE_POD_NAME}
              targets:
                - 0.0.0.0:8888
          {{ end }}
      {{ end }}
    processors:
      {{- toYaml $collector.config.processors | nindent 6 }}
    service:
      {{- toYaml $collector.config.service | nindent 6 }}
  resources:
    {{- toYaml $collector.resources | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "{{ $.Release.Name }}-{{ $collector.name }}"
rules:
- apiGroups: [""]
  resources:
  - nodes
  - nodes/proxy
  - nodes/metrics
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: ["monitoring.coreos.com"]
  resources:
  - servicemonitors
  - podmonitors
  verbs: ["get", "list", "watch"]
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs: ["get", "list", "watch"]
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs: ["get", "list", "watch"]
- nonResourceURLs: ["/metrics", "/metrics/cadvisor"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "{{ $.Release.Name }}-{{ $collector.name }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "{{ $.Release.Name }}-{{ $collector.name }}"
subjects:
- kind: ServiceAccount
  # quirk of the Operator
  name: "{{ $.Release.Name }}-{{ $collector.name }}-collector"
  namespace: {{ $.Release.Namespace }}
{{- if eq $collector.mode "statefulset" }}
- kind: ServiceAccount
  name: {{ $.Release.Name }}-collector-targetallocator
  namespace: {{ $.Release.Namespace }}
{{- end }}
---
{{ end }}
{{- end }}
