collector:
  # Pinned to a version
  image: otel/opentelemetry-collector-contrib:0.50.0
  env:
    - name: LS_TOKEN
      valueFrom:
        secretKeyRef:
          key: LS_TOKEN
          name: otel-collector-secret
  resources:
    limits:
      cpu: 2000m
      memory: 3000Mi
    requests:
      cpu: 1000m
      memory: 2500Mi
  config:
    exporters:
      logging:
        loglevel: info
        sampling_initial: 10
        sampling_thereafter: 1000000
    processors:
      memory_limiter:
        check_interval: 1s
        limit_mib: 2000
      resourcedetection/gke:
        detectors: [env, gke]
        timeout: 2s
        override: false
      batch:
        send_batch_size: 1000
        timeout: 1s
        send_batch_max_size: 1500
      resource:
        attributes:
        - key: job
          from_attribute: service.name
          action: insert
        - key: instance
          from_attribute: service.instance.id
          action: insert
        - key: cloud_platform
          from_attribute: cloud.platform
          action: insert
        - key: cloud_provider
          from_attribute: cloud.provider
          action: insert
        - key: http.scheme
          action: delete
        - key: instrumentation.name
          action: delete
        - key: net.host.name
          action: delete
        - key: net.host.port
          action: delete
        - key: service.instance.id
          action: delete
        - key: service.name
          action: delete
        - key: cloud.platform
          action: delete
        - key: cloud.provider
          action: delete
    exporters:
      otlp:
        endpoint: ingest.lightstep.com:443
        tls:
          insecure_skip_verify: true
        headers:
          "lightstep-access-token": "${LS_TOKEN}"
      logging:
        loglevel: debug

    service:
      pipelines:
        metrics:
         receivers: [prometheus]
         processors: [memory_limiter, resourcedetection/gke, resource, batch]
         exporters: [otlp]
