{{ $collectorList := (append (append .Values.collectors .Values.tracesCollector) .Values.metricsCollector) }}
{{ range $_, $collector := $collectorList -}}
{{ if $collector.enabled }}
{{ $collectorName := (print $.Release.Name "-" $collector.name) }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ $collectorName }}-collector
  labels:
{{ include "kube-otel-stack.labels" $ | indent 4 }}
spec:
  endpoints:
  - path: /metrics
    port: monitoring
  namespaceSelector:
    matchNames:
    - opentelemetry
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $collectorName }}-collector-monitoring
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ $collectorName }}-targetallocator
  labels:
{{ include "kube-otel-stack.labels" $ | indent 4 }}
spec:
  endpoints:
  - path: /metrics
    port: targetallocation
  namespaceSelector:
    matchNames:
    - opentelemetry
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $collectorName }}-targetallocator
{{ end }}
{{ end }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-operator
  labels:
{{ include "kube-otel-stack.labels" $ | indent 4 }}
spec:
  endpoints:
  - path: /metrics
    port: metrics
  namespaceSelector:
    matchNames:
    - opentelemetry
  selector:
    matchLabels:
      app.kubernetes.io/name: opentelemetry-operator