{{ range $_, $collector := .Values.collectors -}}
{{ if $collector.enabled }}
{{ $collectorName := (print $.Release.Name "-" $collector.name) }}
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: "{{ $collectorName }}"
spec:
  mode: {{ $collector.mode }}
  image: {{ $collector.image }}
  replicas: {{ $collector.replicas | default 1 }}
  ports:
    - name: "metrics"
      protocol: TCP
      port: 8888
  env:
    {{- toYaml $collector.env | nindent 4}}
    - name: K8S_NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: K8S_POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
  config: |
    exporters:
      {{- toYaml $collector.config.exporters | nindent 6 }}
    receivers:
      {{- toYaml $collector.config.receivers | nindent 6 }}
    processors:
      {{- toYaml $collector.config.processors | nindent 6 }}
    service:
      {{- toYaml $collector.config.service | nindent 6 }}
  resources:
    {{- toYaml $collector.resources | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "{{ $collectorName }}"
rules:
- apiGroups: [""]
  resources:
    - events
    - namespaces
    - namespaces/status
    - nodes
    - nodes/spec
    - nodes/stats
    - nodes/proxy
    - pods
    - pods/status
    - replicationcontrollers
    - replicationcontrollers/status
    - resourcequotas
    - services
  verbs: ["get", "list", "watch"]
- apiGroups:
    - batch
  resources:
    - jobs
    - cronjobs
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - autoscaling
  resources:
    - horizontalpodautoscalers
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - extensions
  resources:
    - ingresses
    - daemonsets
    - deployments
    - replicasets
  verbs: ["get", "list", "watch"]
- apiGroups:
    - apps
  resources:
    - daemonsets
    - deployments
    - replicasets
    - statefulsets
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - networking.k8s.io
  resources:
    - ingresses
  verbs: ["get", "list", "watch"]
- nonResourceURLs: ["/metrics", "/metrics/cadvisor"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "{{ $collectorName }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "{{ $collectorName }}"
subjects:
- kind: ServiceAccount
  # quirk of the Operator
  name: "{{ $collectorName }}-collector"
  namespace: {{ $.Release.Namespace }}
---
{{ end }}
{{- end }}
